version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      TEST_REDIS_URL: redis://cache_server:6379
    command: npm run test:ci
    depends_on:
      - cache_server
  cache_server:
    image: "redis:alpine"
